name: layout_simulator
description: LayoutSimulator can simulate app layout with any screen size, orientation and text scale.
version: 0.3.0
homepage: https://github.com/wasitu/flutter-layout_simulator

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    # - ios-bar-black.png
    # - ios-bar-white.png
  fonts:
    - family: apple_icon
      fonts:
        - asset: assets/apple_icon.ttf